coverage:
    status:
        project:
            default:
                # basic
                target: auto
                threshold: 0.1%
        patch:
            default:
                # basic
                target: auto
                threshold: 0.1%
