# Orchestrator configuration options
[orchestrator]
# If the built-in relayer is enabled, this relayer is configured in the [relayer] section
relayer_enabled = true

[relayer]
valset_market_enabled = false
batch_market_enabled = true
logic_call_market_enabled = true