[default]
src = 'src'                                             # the source directory
test = 'test'                                                 # the test directory
out = 'out'                                                   # the output directory (for artifacts)
libs = ['lib']                                                # a list of library directories
remappings = ['ds-test/=lib/ds-test/src/','forge-std/=lib/forge-std/src/']                                               # a list of remappings
cache = false                                                 # whether to cache builds or not
evm_version = 'london'                                        # the evm version (by hardfork name)
solc_version = '0.8.10'                                       # override for the solc version (setting this ignores `auto_detect_solc`
optimizer = true                                              # enable or disable the solc optimizer
optimizer_runs = 200                                          # the number of optimizer runs
fuzz_runs = 10000
fuzz_max_local_rejects = 65536                                # max number of individual inputs that may be rejected before the test aborts
fuzz_max_global_rejects = 1024                                # max number of combined inputs that may be rejected before the test aborts
ffi = false                                                   # whether to enable ffi or not
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'         # the address of `msg.sender` in tests
initial_balance = '0xffffffffffffffffffffffff'                # the initial balance of the test contract
gas_limit = 9223372036854775807                               # the gas limit in tests
gas_reports = ["*"]                                           # a list of contracts to output gas reports for