# exclude non-core contracts from coverage analysis
reports:
  exclude_paths:
    - contracts/helper/test/*.*

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
