codeSize: 0xF4240
balanceAddr: 100000000000000000000
cryticArgs: # If we add more dependencies they will need to be added as symlinks here!
  ["--solc-remaps", "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"]
